---
driver:
  name: ec2
  region: us-west-2
  instance_type: t2.micro
  subnet_id: subnet-19ac017c
  tags:
    Name: <%= ENV['KITCHEN_INSTANCE_NAME'] || 'delivery-sugar-kitchen' %>

transport:
  ssh_key: <%= ENV['KITCHEN_EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: ubuntu-14.04
    driver:
      image_search:
        name: ubuntu/images/*/ubuntu-*-14.04-*-server-*
        owner-id: "099720109477"
        architecture: x86_64
        virtualization-type: hvm
        block-device-mapping.volume-type: gp2
        image-type: machine

suites:
  - name: default
    run_list:
      - recipe[test-build-cookbook::default]
    attributes:
