# Don't worry about the number of spaces between param and value.
# This is used for styling in some Chef files.
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

# Don't force us to write documentation
Documentation:
    Enabled: false
